# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfcbbb42aefb4faee0f6eb4b9654166eb07280fd3fd21e79a8af4cee1c807ee4e22286c7f65562b00ba07936958e9cd78e9439eb6e40838e93d391ae3fa06d55

test:
  secret_key_base: 4e89230ccc8b76432f9b0b5a96ddf31890baf80076d1f1a7abcfe815704ac253388db8f1da65425f355e0c16fa6fe4b91d0c403c64bc9e7ad1058497d1404c54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
